runtime: custom
env: flex

env_variables:
  WHITELIST: ENV_WHITELIST
  CDN_HOSTNAME: ENV_CDN_HOSTNAME

# instance_class: B8
manual_scaling:
  instances: 2

beta_settings:
  cloud_sql_instances: CLOUD_SQL_CONNECTION_NAME